### ISSUE TITLE
DMS error extracting ZPKM.artcc

### ISSUE THREAD

**Issue by Tatpolc** [ivao-in/sector_file_creator#1]
There was a bug extracting the ZPKM FIR data, the DMS coordinate becomes:
N33.34.59.1000;E103.52.59.1000;

While it should be:
N33.34.59.100;E103.52.59.100;

<img width="266" alt="image" src="https://github.com/user-attachments/assets/8c166274-1bd5-4ad8-8c35-64e70a5e7ed2">

**Comment by APRILDAY23** [comment]
Hello @Tatpolc 
Thank you for your report. I will have a look why its generating wrong ms. I will implement the fix in the next release v1.0.4

**Comment by APRILDAY23** [comment]
Hello @Tatpolc 
The issue has been fixed, Thanks!! I will release it in the next version
![image](https://github.com/user-attachments/assets/b6a1468a-eaf0-46f0-a3f6-e3b4c764d80d)
![image](https://github.com/user-attachments/assets/f322f1c0-c675-4e8b-bd3a-0d6c377b319b)
